root: true
extends:
  - '@atomix'
parser: vue-eslint-parser
parserOptions:
  ecmaVersion: 2017
  allowImportExportEverywhere: true
plugins:
  - vue
rules:
  # no-console: 0
  # no-extend-native: 0
  comma-dangle:
    - error
    - always-multiline
  unicorn/filename-case: off
  no-trailing-spaces: off
  eol-last: off
